### ISSUE TITLE
Compiler Roadmap (v1.0.0)

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/style#5]
This issue contains the roadmap for Style's compiler, up till v1.0.0.

**Properties**
- [ ] Accent (`accent-color`)
- [ ] Animate (`animation`)
- [ ] Backdrop-Blur (`backdrop-filter`)
- [ ] Backdrop-Brightness (`backdrop-filter`)
- [ ] Backdrop-Contrast (`backdrop-filter`)
- [ ] Backdrop-Grayscale (`backdrop-filter`)
- [ ] Backdrop-Hue (`backdrop-filter`)
- [ ] Backdrop-Invert (`backdrop-filter`)
- [ ] Backdrop-Opacity (`backdrop-filter`)
- [ ] Backdrop-Saturate (`backdrop-filter`)
- [ ] Backdrop-Sepia (`backdrop-filter`)
- [ ] Background-Blend (`background-blend-mode`)
- [ ] Blur (`filter`)
- [X] Box (`box-sizing`, `box-decoration-break`)
- [X] Break (`break-before`, `break-after`, `break-inside`)
- [ ] Brightness (`filter`)
- [ ] Caret (`caret-color`)
- [ ] Color-Adjust (`forced-color-adjust`)
- [ ] Contrast (`filter`)
- [ ] Decorate (`text-decoration`, `text-decoration-style`, `text-decoration-color`, `text-decoration-weight`, `text-underline-offset`)
- [ ] Divide (`* + *`, `border-left-width`, `border-right-width`, `border-top-width`, `border-bottom-width`, `border-style`, `border-color`)
- [ ] Drop-Shadow (`filter`)
- [ ] Flex (`display: flex`, `flex-direction`, `justify-content`, `align-items`, `flex-basis`, `flex-wrap`)
- [ ] Font (`font-family`)
- [ ] Grayscale (`filter`)
- [ ] Grid (`display: grid`, `grid-template-columns`, `grid-template-rows`, `justify-items`, `align-content`)
- [ ] Hue (`filter`)
- [ ] Hypen (`hyphens`)
- [ ] Invert (`filter`)
- [X] Isolate (`isolation`)
- [ ] Letter (`letter-spacing`)
- [ ] Line (`line-height`, `overflow: hidden`, `display: -webkit-box`, `-webkit-box-orient: vertical`, `-webkit-line-clamp`)
- [ ] List (`list-style-type`, `list-style-image`, `list-style-position`)
- [ ] Mix-Blend (`mix-blend-mode`)
- [ ] Object (`object-fit`, `object-position`)
- [ ] Overscroll (`overscroll-behavior`)
- [ ] Visible (`visibility`)
- [X] Ratio (`aspect-ratio`)
- [ ] Ring (`box-shadow`)
- [ ] Rotate (`transform`, `transform-origin`)
- [ ] Saturate (`filter`)
- [ ] Scale (`transform`, `transform-origin`)
- [ ] Screen-Reader (`position`, `width`, `height`, `padding`, `margin`, `overflow`. `clip`, `white-space`, `border-width`)
- [ ] Scroll (`scroll-behavior`, `scroll-margin`, `scroll-padding`, `scroll-snap-align`, `scroll-snap-stop`, `scroll-snap-type`)
- [ ] Select (`user-select`)
- [ ] Sepia (`filter`)
- [ ] Shadow (`box-shadow`)
- [ ] Size (`width`, `height`)
- [ ] Skew (`transform`, `transform-origin`)
- [ ] Space (`* + *`, `margin-left`, `margin-top`)
- [ ] Stroke (`stroke`, `stroke-width`)
- [ ] Text (`color`, `font-size`, `font-weight`, `text-align`, `text-overflow`, `text-wrap`, `text-transform`, `text-indent`)
- [ ] Touch (`touch-action`)
- [ ] Translate (`transform`, `transform-origin`)
